### ISSUE TITLE
PHP CS Fixer: php general error

### ISSUE THREAD

**Issue by jorendemaeyer1996** [junstyle/vscode-php-cs-fixer#2]
When i try to save a file i get the error 'PHP CS Fixer: php general error'

When i try to run php-cs-fixer fix . from the terminal it formats all my files correctly ...

Some help please?
<img width="1069" alt="screen shot 2017-03-01 at 13 15 12" src="https://cloud.githubusercontent.com/assets/16215602/23459638/8b86ed6a-fe81-11e6-81ee-7f302f3039e1.png">
![screen shot 2017-03-01 at 13 16 16](https://cloud.githubusercontent.com/assets/16215602/23459639/8b886852-fe81-11e6-9224-743046db7cbd.png)

**Comment by junstyle** [comment]
you can see php cs fixer error code at [https://github.com/FriendsOfPHP/PHP-CS-Fixer#exit-codes](https://github.com/FriendsOfPHP/PHP-CS-Fixer#exit-codes).  
1 General error (or PHP/HHVM minimal requirement not matched).

and install php cs fixer follow this page: [https://github.com/FriendsOfPHP/PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)

**Comment by junstyle** [comment]
which version php-cs-fixer do you install? 
`php-cs-fixer -v`
^2.0.0

**Comment by jorendemaeyer1996** [comment]
![screen shot 2017-03-02 at 15 13 27](https://cloud.githubusercontent.com/assets/16215602/23510689/d13f55fc-ff5a-11e6-8ebf-151c101646f9.png)

**Comment by junstyle** [comment]
you can open developer tools and see the logs
vs code: Help->Toggle Developer Tools

**Comment by jerryluo** [comment]
I had the same error before and I solved it by running visual studio code as Administrator.

My environment:
Windows 8.1
PHP Version 5.4.31

VS setting for the extension:
{
    "php-cs-fixer.executablePath": "C:\\php-cs-fixer.phar",
    "php-cs-fixer.onsave": false,
    "php-cs-fixer.rules": "@PSR2",
    "php-cs-fixer.autoFixByBracket": true,
    "php-cs-fixer.autoFixBySemicolon": false,
    "php-cs-fixer.formatHtml": true,
}

VS code installed path:
C:\Program Files (x86)\Microsoft VS Code\

**Comment by jorendemaeyer1996** [comment]
@jerryluo Any idea how this can be be done on Mac?

**Comment by jerryluo** [comment]
@jorendemaeyer1996 I am still trying to figure out how to do this on mac, will post it here if I find the solution.

**Comment by junstyle** [comment]
@jorendemaeyer1996 try full path of php-cs-fixer on mac.
"php-cs-fixer.executablePath": "/usr/local/bin/php-cs-fixer",
or install by composer:
"php-cs-fixer.executablePath": "/Users/[username]/.composer/vendor/bin/php-cs-fixer",

**Comment by jsorroche** [comment]
I found that disabling the caching mechanism solves the problem...

This is a temporary fix to make the php-cs-fixer work.

**Comment by joetsuihk** [comment]
Error is `Failed to write file ".php_cs.cache", "no reason available". `

disable cache by config file .php_cs:
```
<?php

return PhpCsFixer\Config::create()
    ->setUsingCache(false)
;
```

Mac 10.11, VSCode 1.11.1, php-cs-fixer v2.2.1

**Comment by junstyle** [comment]
I have released a new version and added '--using-cache=no', cache is useless for single file.

**Comment by dheerajwebkul** [comment]
VS Code: V1.16.0
OS: Ubuntu 14.04
php cs fixer V0.1.43

Hello @junstyle 

I still have this issue in this latest fixer version.
Where I can set this '--using-cache=no' ?

**Comment by junstyle** [comment]
--using-cache=no  is default, you don't need add any config

**Comment by dheerajwebkul** [comment]
Ok thanks @junstyle 
But still
PHP CS Fixer: php general error
is there.

And I can fix the error by console command.

Is there any idea, How can I fix this?
Tahnks,

**Comment by junstyle** [comment]
vsc menu: Help->Toggle Developer Tools, see log infomation in console tab.

**Comment by dheerajwebkul** [comment]
@junstyle 
This comes in the console: (3 Errors)

1) [Extension Host]                        extensionHost.ts:384               
  [RuntimeException]                          
  The "--using-cache" option does not exist.  

2) [Extension Host] fix [--config CONFIG] [--config-file [CONFIG-FILE]] [--dry-run] [--level LEVEL] [--fixers FIXERS] [--diff] [--format FORMAT] [--] [<path>]                                                         extensionHost.ts:384

3) (node:3419) DeprecationWarning: Calling an asynchronous function without callback is deprecated.                          extensionHost.ts:384

Thanks,

**Comment by junstyle** [comment]
> The "--using-cache" option does not exist.

your php-cs-fixer is not latast version?
https://github.com/FriendsOfPHP/PHP-CS-Fixer download new version

**Comment by dheerajwebkul** [comment]
Thanks @junstyle 
Updating the php-cs-fixer version solved the issues.

Thanks,

**Comment by TiagoSilvaPereira** [comment]
.I've this error with php-cs-fixer v2.8.3:

[Extension Host] Error: spawn php-cs-fixer ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by junstyle** [comment]
“spawn php-cs-fixer ENOENT”
means
php-cs-fixer not found
"php-cs-fixer": "/your/php-cs-fixer/fullpath";
